#!/usr/bin/env zsh
# vim: set filetype=zsh

# General configurations
#############################
# Disable magic functions to avoid conflicts with other plugins
# Added to fix pasting in the terminal, for example: wget http://{DEFAULT_IP}/index.html
export DISABLE_MAGIC_FUNCTIONS=true
# Set XDG_CONFIG_HOME
export XDG_CONFIG_HOME="${HOME}/.config"
# Set the GPG_TTY to the current TTY
# export GPG_TTY=${TTY}
# Use case-sensitive completion
export CASE_SENSITIVE="true"

# FZF configuration
#############################
export FZF_DEFAULT_COMMAND="${FZF_DEFAULT_COMMAND}"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color=dark,fg:7,bg:-1,hl:5,fg+:15,bg+:8,hl+:13,info:2,prompt:4,pointer:1,marker:3,spinner:4,header:4"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --layout=reverse --inline-info --preview-window=right:60%:wrap --border -x"

# Autosuggestions configuration
#############################
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=242"

# Starship configuration
#############################
export STARSHIP_CONFIG="${HOME}/.config/starship/starship.toml"
