# vim: foldmethod=marker
# Oh-My-Zsh {{{1

export ZSH="${HOME}/.oh-my-zsh"
export ZSH_CUSTOM="${ZSH}/custom"

# Load zsh plugins
plugins=(
    F-Sy-H # alternative to zsh-users/zsh-syntax-highlighting
    colored-man-pages # Adds color to man pages
    sudo  # To toggle with ESC the sudo usage
    fzf-tab # FZF integration for tab completion
    zsh-autosuggestions # Zsh plugin for fish-like autosuggestions
    # zoxide
)

# Load oh-my-zsh
source "${ZSH}/oh-my-zsh.sh"

# Apply sensisble zsh settings
source $HOME/.zshopt

# Source files {{{2
# Load aliases
source $ZSH_CUSTOM/aliases.zsh

# Apply styles configuration
source $ZSH_CUSTOM/styles.zsh

eval "$(starship init zsh)"
